config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # 以下的寫法除了為:todos建出基本的7個CRUD動作之外，可以為:is_done做出包含prefix在內都有子母關係的路由
  # ---------------------------------------------------------------------------------------
  # Prefix       Verb   URI Pattern                  Controller#Action
  # is_done_todo PATCH  /todos/:id/is_done(.:format) todos#is_done
  #        todos GET    /todos(.:format)             todos#index
  #              POST   /todos(.:format)             todos#create
  #     new_todo GET    /todos/new(.:format)         todos#new
  #    edit_todo GET    /todos/:id/edit(.:format)    todos#edit
  #         todo GET    /todos/:id(.:format)         todos#show
  #              PATCH  /todos/:id(.:format)         todos#update
  #              PUT    /todos/:id(.:format)         todos#update
  #              DELETE /todos/:id(.:format)         todos#destroy
  # ---------------------------------------------------------------------------------------
  # resources :todos do
  #   member do
  #     patch :is_done
  #   end
  # end


  # ---------------------------------------------------------------------------------------
  # Prefix    Verb   URI Pattern                  Controller#Action
  # todos     GET    /todos(.:format)             todos#index
  #           POST   /todos(.:format)             todos#create
  # new_todo  GET    /todos/new(.:format)         todos#new
  # edit_todo GET    /todos/:id/edit(.:format)    todos#edit
  # todo      GET    /todos/:id(.:format)         todos#show
  #           PATCH  /todos/:id(.:format)         todos#update
  #           PUT    /todos/:id(.:format)         todos#update
  #           DELETE /todos/:id(.:format)         todos#destroy
  #           PATCH  /todos/:id/is_done(.:format) todos#done
  # ---------------------------------------------------------------------------------------
  resources :todos
  patch "/todos/:id/is_done", to: "todos#done"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates_presence_of :name, :due_date
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :target_todo, :only => [:show, :edit, :update, :destroy, :done]
  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      redirect_to todos_path
    else
      render :action => :new
    end
  end

  def edit
  end

  def update
    if @todo.update_attributes(todo_params)
      redirect_to todos_path
    else
      render :action => :edit
    end
  end

  def show
  end

  def destroy
    @todo.destroy
    redirect_to todos_path
  end

  def done
    @todo.is_done = !(@todo.is_done)
    @todo.save
    redirect_to todos_path
  end

  private
  def todo_params
    params.require(:todo).permit(:name, :due_date, :note)
  end

  def target_todo
    @todo = Todo.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<% if @todo.errors.present? %>
  <ul>
    <% @todo.errors.each do |error, message| %>
      <li> <%= "#{error.capitalize}  #{message}" %></li>
    <% end %>
  </ul>
<% end %>

<div class="form container">
  <%= form_for @todo do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :due_date %>
      <%#= f.text_field :due_date, class: "form-control" %>
      <%= f.datetime_select :due_date, :start_year=>2018,:end_year=>2030 %>
    </div>
    <div class="form-group">
      <%= f.label :note %>
      <%= f.text_field :note, class: "form-control" %>
    </div>
    <%= f.submit %>
  <% end %>
</div>

app/views/todos/edit.html.erb
<%= render :partial => "form" %>

app/views/todos/index.html.erb
<div class="container">
  <h1 class="text-center">Mew's Todo-List</h1>
  
  <div class="col-xs-12">
    <div class="col-xs-6" style="vertical-align: middle">
      <h3 class="text-center"><span class="glyphicon glyphicon-time"></span> Current Time</h3>
      <h5 class="text-center"><%= Time.now %></h3>
    </div>
    <div class="col-xs-6">
      <%= link_to new_todo_path do %>
        <h3 class="text-center"><span class="glyphicon glyphicon-plus-sign"></span> Add New Todo Item</h3>
      <% end %>
    </div>
  </div>
  
  
  <table class="table table-striped table-condensed">
    <tr>
      <td><span class="glyphicon glyphicon-ok-circle"></span> Done</td>
      <td><span class="glyphicon glyphicon-pushpin"></span> Name</td>
      <td><span class="glyphicon glyphicon-calendar"></span> Deadline</td>
      <td><span class="glyphicon glyphicon-edit"></span> Edit</td>
      <td><span class="glyphicon glyphicon-trash"></span> Destroy</td>
    </tr>
    <% @todos.each do |todo| %>
    <tr>
      <% if (Time.now - todo.due_date) <= 0 %>
        <td>
          <%= link_to todo_path(todo)+"/is_done", method: :patch, data:{ confirm: "Done?"} do%>
            <% if todo.is_done == true %>
              <span class="glyphicon glyphicon-check"></span>
            <% else %>
              <span class="glyphicon glyphicon-unchecked"></span>
            <% end %>
          <% end %>
        </td>
      <% else %>
        <td>
          <% if todo.is_done == true %>
            <span class="glyphicon glyphicon-check"></span>
          <% else %>
            <span class="glyphicon glyphicon-unchecked"></span>
          <% end %>
        </td>
      <% end %>

        <td><%= todo.name %></td>

        <td><%= todo.due_date.to_date %></td>

      <% if (Time.now - todo.due_date) <= 0 %>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= link_to 'Destroy', todo_path(todo), method: :delete, data:{ confirm: "Are you sure?"} %></td>
      <% else %>
        <td><p>Expired</p></td>
        <td><p>Expired</p></td>
      <% end %>
    </tr>
    <% end %>
  </table>
</div>

app/views/todos/new.html.erb
<%= render :partial => "form" %>